name: Deploy

on:
  push:
    branches: 
     - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }} 
          known_hosts: 'hello-world'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: sync
        run: |
          rsync -avz artifact/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/html/tmp/${{ github.event.repository.name }}
      - name: deploy
        run: |
          ssh  ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'rsync -va /var/www/html/tmp/${{ github.event.repository.name }}/ /var/www/html/simple-html/'